class TTConfig:
    def __init__(self):
        pass

    SERVER_CONFIG = {
        "a-2g": 8,
        "a-3g": 24,
        "a-constraints": {
          "googNoiseSuppression": "true",
          "googHighpassFilter": "false",
          "googTypingNoiseDetection": "false",
          "googAudioNetworkAdaptorConfig": ""
        },
        "a-lte": 24,
        "a-wifi": 34,
        "account-removal-enabled": False,
        "animated-emojis": {},
        "animated-emojis-limits": {
          "low": 5,
          "average": 10,
          "high": 15
        },
        "animated-emojis-places": [
          "MESSAGE_NORMAL_TEXT",
          "MESSAGE_BIG_EMOJI_TEXT",
          "MESSAGE_INPUT",
          "STICKERS_KEYBOARD",
          "CHATS_LIST"
        ],
        "attachment-popup-click": False,
        "audio-transcription-enabled": True,
        "audio-transcription-locales": [
          "ru"
        ],
        "change-self-readmark-on-msg-send": False,
        "chat-bg": False,
        "chat-cancel-top-menu-enabled": False,
        "chat-filter": False,
        "chat-info-full-list-enabled": False,
        "chat-preview-enabled": False,
        "chats-edit-enabled": False,
        "chats-folder-enabled": True,
        "chats-list-promo-link-enabled": False,
        "chats-page-size": 50,
        "chats-preload-period": 15,
        "close-keyboard-on-scroll": True,
        "common-chats-enabled": True,
        "compact-mode-enabled": False,
        "congrats-banner-enabled-mob": False,
        "congrats-banner-enabled-web": True,
        "contact-verify-enabled": False,
        "contacts-send": False,
        "contacts-sort-refresh": 259200,
        "copy-id-btn": False,
        "debug-mode": 1,
        "delayed-messages": False,
        "delayed-messages-enabled": False,
        "detect-share-when-send-message": True,
        "dialog-priority": False,
        "disconnect-timeout": 300,
        "drafts-sync-enabled": True,
        "edit-timeout": 86400,
        "expandable-appbar-enabled": True,
        "experimental": False,
        "fast-chat-actions-enabled": False,
        "file-upload-enabled": True,
        "file-upload-max-size": 2147483648,
        "file-upload-unsupported-types": [
          "exe"
        ],
        "gce": True,
        "hashtags-enabled": True,
        "html-paste": False,
        "http-logs-enabled": False,
        "image-height": 1680,
        "image-quality": 0.800000011920929,
        "image-size": 40000000,
        "image-width": 1680,
        "invite-header": "",
        "invite-link": "",
        "invite-long": "",
        "invite-short": "",
        "keep-connection": 2,
        "l10n": False,
        "live-location-enabled": True,
        "location-enabled": True,
        "logs-enabled": True,
        "markdown-enabled": True,
        "markdown-menu": 0,
        "markdown-miui-enabled": True,
        "max-audio-length": 3600,
        "max-cname-length": 200,
        "max-description-length": 400,
        "max-favorite-chats": 5,
        "max-favorite-sticker-sets": 100,
        "max-favorite-stickers": 100,
        "max-msg-length": 4000,
        "max-participants": 20000,
        "max-readmarks": 300,
        "max-theme-length": 200,
        "max-video-duration-download": 1200,
        "mediabar-scroll-layout": True,
        "mentions-enabled": True,
        "mentions_entity_names_limit": 3,
        "min-image-side-size": 64,
        "moderated-groups": False,
        "moderated-groups-filter": False,
        "multiselect": True,
        "music-files-enabled": False,
        "muted-chat-call-enabled": False,
        "nearby-timeouts": {
          "enabled": "True",
          "LaunchBroadcastTime": "0",
          "LaunchBroadcastTimeLimit": "300",
          "ContactsScreenBroadcastTime": "10",
          "ChatSearchScreenBroadcastTime": "10",
          "RecentContactTime": "300"
        },
        "new-chats-searching": True,
        "new-chats-ui": True,
        "new-fcm-push": True,
        "notif-images": True,
        "offline-icon": False,
        "often-chats": False,
        "ok-avatar-icon": False,
        "ok-profile-unbind-enabled": True,
        "ok-tt-chat-separation": True,
        "one-chat-enabled": False,
        "one-chat-new-panel-sticker": False,
        "peer-connection-params": {
          "ebv": [
            "xiaomi",
            "huawei"
          ],
          "ebm": [
            "oneplus a5010"
          ]
        },
        "phone-bind-enabled": True,
        "phone-layer-enabled": True,
        "play-background-listen-to-end": False,
        "play-next-audio": False,
        "plus-menu-enabled": False,
        "prefs": 1,
        "profile-autodelete-enabled": True,
        "profiling-enabled": False,
        "progress-diff-for-notify": 1,
        "promo-contact-id": 0,
        "promo-recent-contacts": False,
        "promo_contact_label": "",
        "proxy": "",
        "proxy-domains": [],
        "proxy-exclude": [],
        "proxy-rotation": False,
        "push-alert-timeout": 604800,
        "push-tracking-enabled": True,
        "quick-forward-cases": [],
        "react-permission": 2,
        "reactions-enabled": True,
        "reactions-max": 3,
        "reactions-menu": [
          "👍",
          "❤️",
          "💩",
          "😂",
          "🔥",
          "🙏",
          "👎",
          "😮"
        ],
        "readmark-enabled-delay-ms": 400,
        "remove-profile-enable": True,
        "remove-user-msg-del": True,
        "retry-sig-count": 5,
        "retry-sig-delay": 4,
        "screen-share-enabled": False,
        "screen-sharing-enabled": True,
        "send-media-from-system-keyboard": False,
        "send-side-bwe": True,
        "send-system-keyboard-png-as-stickers": True,
        "set-unread-timeout": 31536000,
        "settings-use": False,
        "show-invited-by": True,
        "show-rm-limits": [
          15,
          100
        ],
        "show-snow": True,
        "sticker-gif-enabled": True,
        "sticker-sections": [
          "TOP",
          "NEW"
        ],
        "sticker-sets-links-enabled": True,
        "sticker-suggest-disabled": False,
        "stickers-suggestion": [
          "RECENT",
          "NEW",
          "TOP"
        ],
        "stickers-suggestion-keywords-inline": False,
        "support-account": "",
        "support-button-enable": False,
        "t-ice-reconnect": 15,
        "t-incoming-call": 40,
        "t-start-connect": 20,
        "tam-emoji-font-url": "",
        "tcp-candidates": False,
        "tracer-crash-report-enabled": False,
        "tracer-crash-report-host": "",
        "tracer-crash-send-asap-enabled": False,
        "tracer-crash-send-logs-enabled": False,
        "tracer-crash-send-threads-dump-enabled": False,
        "tracer-disk-overflow-report-threshold": 3000000000,
        "tracer-disk-usage-probability": 500,
        "tracer-enabled": False,
        "tracer-host": "",
        "tracer-hprof-probability": -1,
        "tracer-sampled-conditions": "",
        "tracer-sampled-duration": 20000,
        "tracer-systrace-duration": 20000,
        "tracer-systrace-interesting-duration": 10000,
        "tracer-systrace-probability": 10000,
        "unknown-person-attention": True,
        "unread-filter-enabled": False,
        "update-non-contacts": 10,
        "use-congrats-list-in-mass-sending": False,
        "use-new-message-rendering": True,
        "v-2g": 128,
        "v-3g": 1024,
        "v-fps": 24,
        "v-fps-v8": 20,
        "v-height": 720,
        "v-height-vp8": 480,
        "v-lte": 1024,
        "v-vp8": 512,
        "v-width": 1280,
        "v-width-vp8": 640,
        "v-wifi": 2048,
        "vce": True,
        "video-attach-download-enabled": False,
        "video-auto-compress-enabled": True,
        "video-messages": False,
        "video-params": True,
        "video-preview": "480x270",
        "wakelock-on-push": False,
        "wm-analytics-enabled": True,
        "wm-workers-limit": 80,
        "iceServers": [],
        "has-phone": True,
        "promo-constructors": []
      }
